Clarifai/examples

README.md
datasets/export/download_export_archive.py
models/model_predict.ipynb

- Add Model Predict examples `model_predict.ipynb`
- Covers all input types (image, text, audio, video)
- Customising prediction parameters(concepts, threshold..etc)
- Listing of models

[DEVX-153]:  Model Predict Examples

---

README.md
basics/basics.ipynb
datasets/upload/dataset_upload.ipynb
datasets/upload/input_upload.ipynb
models/model_predict.ipynb
workflows/create_workflow.ipynb
workflows/export_workflow.ipynb

- Inputs upload notebook
- with annotation, metadata, geoinfo
-    Updated Readme

input_upload

---

workflows/configs/prompter_llm.yml
workflows/configs/rag_prompter_llm.yml

- Add rag prompter workflow
- Change LLM from open AI to Mistral

Add rag prompter

---

README.md

Changed Demo to Schedule Demo

---

datasets/upload/data/text_prompts.csv
datasets/upload/dataset_upload.ipynb

> Prompt CSV upload for text-to-text use cases

Prompts upload from CSV

---

basics/basics.ipynb
models/model_train/image-classification_training.ipynb
models/model_train/image-detection_training.ipynb
models/model_train/image-segmentation_training.ipynb
models/model_train/text-classification_training.ipynb
models/model_train/transfer-learn.ipynb

- Added different base url operations section in basics.ipynb
- Changed model templates and model types in model training notebooks.

[DEVX-359] : added base url section for basics notebook and changed templates 

---

datasets/upload/dataset_upload.ipynb

1. Included code sample snippets for retry_upload_from_logs functionality.

Added examples for retry_upload_from_logs

---

Integrations/Unstructured/Clarifai_Unstructured_integration_demo.ipynb

Description:
* Example notebook to use unstructured integration with clarifai as destination connector.

Clarifai-unstructured-intg example

---

search/cross_modal_search.ipynb

- Added Pagination in Search
- Added metric, algorithm in Search params

Search Improvements

---

concepts/concept_management.ipynb

Created a new notebook for Concepts Mangement usage. Added snippets of how to use concept relations, concept based searches, etc.

[DEVX-595]: Advanced Concept Mangement

---

models/model_upload/image-classifier/nsfw-image-classifier/config.yaml
models/model_upload/image-detector/detr-resnet-image-detection/config.yaml

- add hf_token field to yaml files of classifier and detector
- manually tested

[PR-161] Add hf_token field to classifier and detector

---

models/model_upload/llms/vllm-mistral-7b-instruct/1/model.py
models/model_upload/llms/vllm-mistral-7b-instruct/config.yaml

- Refracted vLLM LLM example, now the `model.py` code is much more readable
- predict method now calls the generate method in it. This enables processing all items in a batch (request.inputs) in parallel.
Tested this model example locally using local dev runner

[EAGLE-5211] Refracted vLLM LLM example

---

models/model_upload/llms/openai-gpt4/1/model.py
models/model_upload/llms/openai-gpt4/requirements.txt

- **Support Batching efficiently:** Before all the inputs in the batch are not process in parallel in `predict` method which wastes a lot of GPU resources. 
- Batch the inputs and process them together: Instead of processing each input individually, now we batch all the inputs and feed them into the model in one forward pass. This not only utilizes the GPU resources more efficiently but also can significantly speed up the inference time.
- Refracted Openai example, now the `model.py` code is more readable

[EAGLE-5211] Refract Openai GPT4 model

---

CLI/configs/model_predict_config.yaml
CLI/model.ipynb

**Ref -** https://clarifai.atlassian.net/browse/DEVX-839

[DEVX-839]: Added example for  Model Predict CLI

---

Data_Utils/Ingestion pipelines/README.md
README.md

1. For `Data_Utils/Ingestion pipelines/README.md` added the new supported formats
2. For `README.md` added the CLI notebooks

README files update

---

Data_Utils/Ingestion pipelines/Multimodal_ingest_RAG_notebook.ipynb
README.md

Example notebook for multimodal summarizer ingestion into clarifai app.

Multimodal summarizer notebook

---

models/model_upload/test-upload/mbart/1/model.py
models/model_upload/test-upload/mbart/config.yaml
models/model_upload/test-upload/mbart/requirements.txt

Small checkpoint so we can easily test downloads and runtime. I made it CPU only but we should test that it works on GPU as well.

small example using torch

---

Data_Utils/Image Annotation/image_annotation_loader.ipynb
Data_Utils/README.md

Updated the README and example notebook of Image Annotation Loader

[DEVX-890]: Update Image Annotation Loader Notebook

---

models/model_upload/image-classifier/nsfw-image-classifier/1/model.py
models/model_upload/image-detector/detr-resnet-image-detection/1/model.py
models/model_upload/llms/llama-3-8b-instruct/1/model.py
models/model_upload/llms/llama-3_2-1b-instruct/1/model.py
models/model_upload/llms/lmdeploy-llama-3_2-1b-instruct/1/model.py
models/model_upload/llms/openai-gpt4/1/model.py
models/model_upload/llms/vllm-mistral-7b-instruct/1/model.py
models/model_upload/multimodal_models/vllm-miniCPM-2.6/1/model.py
models/model_upload/ocr/got-ocr2.0/1/model.py
models/model_upload/speech-recognition/openai-whisper/1/model.py
models/model_upload/test-upload/mbart/1/model.py
models/model_upload/test-upload/python_string_cat/1/model.py

Updates to examples needed by https://github.com/Clarifai/clarifai-python/pull/494
Also some additional fixes and cleanup to python string cat example model that correct stream behavior and somewhat simplify presentation.

Updates examples for new ModelClass base

---

models/model_upload/llms/llama-3-8b-instruct/requirements.txt
models/model_upload/llms/vllm-mistral-7b-instruct/requirements.txt
models/model_upload/multimodal_models/vllm-miniCPM-2.6/requirements.txt
models/model_upload/ocr/got-ocr2.0/requirements.txt
models/model_upload/test-upload/mbart/requirements.txt

requests==2.32.2 causes conflicts

[PR-493] update requests version

---

models/model_upload/image-classifier/nsfw-image-classifier/config.yaml
models/model_upload/image-detector/detr-resnet-image-detection/config.yaml
models/model_upload/llms/llama-3-8b-instruct/config.yaml
models/model_upload/llms/llama-3_2-1b-instruct/config.yaml
models/model_upload/llms/lmdeploy-llama-3_2-1b-instruct/config.yaml
models/model_upload/llms/sglang-llama-3.3-70b-instruct-awq/config.yaml
models/model_upload/llms/vllm-mistral-7b-instruct/config.yaml
models/model_upload/multimodal_models/vllm-miniCPM-2.6/config.yaml
models/model_upload/ocr/got-ocr2.0/config.yaml

Change catch all NVIDIA str to `NVIDIA-` as `NVIDIA-` is what the backend expects.

change accelerator to NVIDIA-*
